version: '2'
services:
  Test-app:
    image: Test
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://Test-postgresql:5432/Test
      - JHIPSTER_CACHE_REDIS_SERVER=redis://Test-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://Test-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  Test-postgresql:
    extends:
      file: postgresql.yml
      service: Test-postgresql
  Test-redis:
    extends:
      file: redis.yml
      service: Test-redis
