// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_PATTERN = 'LOGIN_';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

export const GET_CARGOS = 'GET_CARGOS';
export const CREATE_CARGOS = 'CREATE_CARGOS';
export const GET_CARGOS_RESPONSE = 'GET_CARGOS_RESPONSE';


export const GET_LOOKUPS_BY_PARENT = 'GET_LOOKUPS_BY_PARENT';
